name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  VERSION: v${{ github.run_number }}

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      #################################################
      # Backend
      #################################################

      - name: Build Backend
        run: |
          docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/k8s-demo-backend:${{ env.VERSION }} \
          ./backend

      - name: Push Backend
        run: |
          docker push \
          ${{ secrets.DOCKER_USERNAME }}/k8s-demo-backend:${{ env.VERSION }}

      #################################################
      # Frontend
      #################################################

      - name: Build Frontend
        run: |
          docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/k8s-demo-frontend:${{ env.VERSION }} \
          ./frontend

      - name: Push Frontend
        run: |
          docker push \
          ${{ secrets.DOCKER_USERNAME }}/k8s-demo-frontend:${{ env.VERSION }}

      #################################################
      # Deploy to Kubernetes
      #################################################

      - name: Deploy
        uses: appleboy/ssh-action@v1.2.2

        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |

            kubectl set image deployment/backend \
            backend=${{ secrets.DOCKER_USERNAME }}/k8s-demo-backend:${{ env.VERSION }}

            kubectl set image deployment/frontend \
            frontend=${{ secrets.DOCKER_USERNAME }}/k8s-demo-frontend:${{ env.VERSION }}

            kubectl rollout status deployment/backend

            kubectl rollout status deployment/frontend